apiVersion: eapapplicationconfig.config.openshift.io/v1alpha1
kind: EAPApplicationConfig
metadata:
  name: example
spec:
  buildConfig:
    type: maven
    mavenBuildConfig:
      source:
        type: Git
        git:
          uri: https://github.com/jboss-developer/jboss-eap-quickstarts
          ref: 6.4.x
        contextDir: kitchensink
