apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: eap-operator 
rules:
- apiGroups:
  - eapapplicationconfig.config.openshift.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:

